bankproject/bankapp/urls.py
from . import views
from django.urls import path
app_name='bankapp'
urlpatterns = [

    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('form',views.form,name='form'),
    path('home',views.home,name='home'),
    path('logout',views.logout,name='logout'),
    path('link',views.link,name='link'),




]

bankproject/bankproject/urls.py
from django.conf import settings
from django.contrib import admin

from django.conf.urls.static import static

from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),


]


if settings.DEBUG:
     urlpatterns+=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
     urlpatterns+=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

bankproject/bankapp/models.py
from django.db import models


class Task(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    img=models.ImageField(upload_to='img')
def __str__(self):
    return self.name

bankproject/bankapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect,reverse


def  register(request):
    if request.method=='POST':

        username=request.POST['username']
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        email= request.POST['email']
        password=request.POST['password']
        cpassword=request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username taken')
                return redirect('/register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,'This field is required')
                return redirect('/register')

            else:

                user=User.objects.create_user(username=username,password=password,first_name=first_name,last_name=last_name,email=email)
                user.save();
                return redirect('/login')
        else:
            messages.info(request,'password not matching')
            return redirect('/register')
        return redirect('/')

    return render(request,"register.html")





def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/home')
        else:
            messages.info(request,"invalid credential")
            return redirect('login')
    return render(request,'login.html')









def form(request):
   if request.method=='POST':
       username = request.POST['username']
       DOB = request.POST['DOB']
       age= request.POST['age']
       phonenumber=request.POST['phonenumber']
       address=request.POST['address']
       user = auth.authenticate(username=username,DOB=DOB,age=age,phonenumber=phonenumber,address=address)

       if User.objects.filter(username=NameError).exists():
           messages.info(request, 'this field is required')
           return redirect('/form')

       else:
           user = User.objects.create_user(username=username)
           user.save();
           return redirect('/link')


   return render(request,"form.html")


def logout(request):
    auth.logout(request)
    return render(request,"logout.html")

def home(request):
    return render(request,"home.html")
def link(request):
    return render(request,"link.html")
    return redirect('/')

bankproject/bankapp/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">



    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src= "https://kit.fontawesome.com/cae219a7d3.js"> </script>

   <meta name="description" content="{% block metadescription %} {% endblock %}" >


    <title>{% block title %}{% endblock %}</title>
</head>
<body>




{% include 'navbar.html' %}


-
    <br>
    <br>

</body>




</html>


<!--<html>-->
<!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
<!-- <link rel="stylesheet" href="{% static 'css/style.css' %}">Indian Bank<br>-->
<!--    Enjoy Banking . . .-->
<!--    <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--<link rel="stylesheet" href="{% static 'css/style.css' %}">-->
<!--<br>-->
<!--         <a class="btn btn-warning" href="{% url 'bankapp:login' %}">Login   </a>-->

<!--          <a class="btn btn-warning" href="{% url 'bankapp:register' %}"> Register  </a>-->
<!--          <a class="btn btn-danger" href="{% url 'bankapp:logout' %}">Logout       </a>-->

<!--        <div class="dropdown-btn">-->
<!--            <div class="dropdown menu">-->
<!--                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--                    Branches-->
<!--                  </button>-->
<!--                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton">-->
<!--                           <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kochi">KOCHI</a></li>-->
<!--                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Aluva">ALUVA</a></li>-->
<!--                             <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Angamaly"> ANGAMALY</a></li>-->
<!--                              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kakkanad">KAKKANAD</a></li>-->
<!--                               <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Vyttila">VYTTILA</a></li>-->
<!--                                           </ul>-->
<!--            </div>-->
<!--        </div>-->

<!--</div>-->
<!--</div>-->
<!--    </nav>-->





<!--    <div class="bg-image d-flex justify-content-center align-items-center"-->
<!--  style="-->
<!--    background-image: url('https://mdbcdn.b-cdn.net/img/new/fluid/nature/015.webp');-->
<!--    height: 100vh;-->
<!--  ">-->

<!--<br>-->
<!--         <br>-->
<!--         <br>-->

<!--    <h4 class="text-white">  Indian Bank-->
<!--        <br>-->
<!--    </h4>-->
<!--         <a class="" href="{% url 'bankapp:link' %}"><h3>Click here...<br>-->
<!--             <br>-->
<!--             To accept the application-->

<!--         </h3></a>-->


<!-- - -->
<!--    <br>-->
<!--    <br>-->





<!--</div></html>-->

bankproject/bankapp/templates/form.html
{% load static %}
<br>
REGISTRATION FORM

    <link href="{% static 'css/reg.css' %}" rel="stylesheet">
<form action="form" method="Post">
  {% csrf_token %}
 <br>
 <br>

 NAME: <input type="text" name="username" placeholder="Enter your Name"><br>
 <br>
   DOB:<input type="date" name="DOB" placeholder="Enter your dob"><br>
 <br>
    AGE:<input type="number" name="age" placeholder="Enter your age"><br>
 <br>
    GENDER:<input type="radio" name="gender" placeholder="male"><label>male</label><br>
 <br><input type="radio" name="gender" placeholder="female"><label>female</label><br>
    PHONENO:<input type="number" name="phonenumber" placeholder="Enter phonenumber"><br>
 <br>
    ADDRESS:<input type="text" name="address" placeholder="Enter address"><br>

<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
<script>
var stateObject = {
"ERNAKULAM": {
"Kochi": [],
"Angamaly": [],
"Vyttila":[],
"Kakkanad":[],
},
"TRIVANDRUM": {
"Pattom": [],
"Thambanoor": [],
"Venjaramood":[],
"Vazhuthakkad":[],

}, "KOTTAYAM": {
"Changanassery": [],
"Vaikom": [],
"Puthupally":[],
"Eattumanoor":[],
},
}
window.onload = function () {
var countySel = document.getElementById("countySel"),
stateSel = document.getElementById("stateSel");
for (var country in stateObject) {
countySel.options[countySel.options.length] = new Option(country, country);
}
countySel.onchange = function () {
stateSel.length = 1; // remove all options bar first

if (this.selectedIndex < 1) return; // done
for (var state in stateObject[this.value]) {
stateSel.options[stateSel.options.length] = new Option(state, state);
}
}
countySel.onchange(); // reset in case page is reloaded
stateSel.onchange = function () {
districtSel.length = 1; // remove all options bar first
if (this.selectedIndex < 1) return; // done
var district = stateObject[countySel.value][this.value];
for (var i = 0; i < district.length; i++) {
districtSel.options[districtSel.options.length] = new Option(district[i], district[i]);
}
}
}
</script>
</head>
<body>
<form name="myform" id="myForm">
Select District: <select name="state" id="countySel" size="1">
<option value="" selected="selected">Select District</option>
</select>
<br>
<br>
Select Branch: <select name="countrya" id="stateSel" size="1">
<option value="" selected="selected">Please select district first</option>
</select>
<br>
<br>






<!--    DISTRICT:<input type="text" name="district" placeholder="Enter district"><br>-->
<!--     <option value selected="selected">select District</option>-->
<!--    <option value="Ernakulam">Ernakulam</option>-->

<!--    <option value="ANGAMALI">Trivandrum</option>-->
<!--    <option value="VYTTILA">Kottayam</option>-->

<!-- <br>-->
<!--    BRANCH:<input type="search" name="branch" placeholder="Enter branch name">-->
<!--    <option value selected="selected">select Branches</option>-->
<!--    <option value="KOCHI">KOCHI</option>-->

<!--    <option value="ANGAMALI">ANGAMALI</option>-->
<!--    <option value="KAKKANAD">KAKKANAD</option>-->
<!--    <option value="VYTTILA">VYTTILA</option>-->



    <option value>Select account type</option>
    <input type="radio"  name="account" placeholder="savings"><label>savings</label>
    <input type="radio" name="account"placeholder="current"><label>current</label>
 <br>
    MATERIALS PROVIDED:<br><br>Cheque book <input type="checkbox" name="materials provide" placeholder="enter name of materials provided"><br>
 <br> Credit card<input type="checkbox" name="materials provide" placeholder="enter name of materials provided"><br>
 <br>Debit Card<input type="checkbox" name="materials provide" placeholder="enter name of materials provided"><br>
 <br>

    <input class="btn btn-primary" type="submit">
			<br>
</form></body></html></form>

bankproject/bankapp/templates/header.html
{% extends 'base.html' %}
<header xmlns="http://www.w3.org/1999/html">
    <center>

    <a href=""><img src="{% static 'c1.png' %}" alt="">
    </a>
    </center>
    </header>

bankproject/bankapp/templates/home.html
{% extends 'base.html' %}



<!--{% load static %}-->

<!--<html>-->
<!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--  <div class="container-fluid">-->

<!--    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--&lt;!&ndash;    <nav class="navbar navbar-expand-lg navbar-light bg-light">&ndash;&gt;-->
<!--&lt;!&ndash;<script src= "https://kit.fontawesome.com/cae219a7d3.js"> </script>&ndash;&gt;-->

<!--<br>INDIAN BANK-->

<!--   <div>      <a class="btn btn-warning" href="{% url 'bankapp:login' %}">Login   </a></div>-->
<!--<br>-->
<!--        <div>  <a class="btn btn-warning" href="{% url 'bankapp:register' %}"> Register  </a></div><br>-->
<!--{% if user.is_authenticated %}-->
<!--									<li>Hello....-->
<!--                                        {{user.username}}</li>{% endif %}-->
<!--<div class="dropdown">-->
<!--<link rel="stylesheet" href="{% static 'css/d.css' %}">-->
<!--      <button>Branches</button>-->

<!--<div class="dropdown-content">-->





<!--                           <a href="https://en.wikipedia.org/wiki/Kochi">KOCHI</a>-->
<!--                            <a href="https://en.wikipedia.org/wiki/Aluva">ALUVA</a>-->
<!--                             <a href="https://en.wikipedia.org/wiki/Angamaly"> ANGAMALY</a>-->
<!--                              <a href="https://en.wikipedia.org/wiki/Kakkanad">KAKKANAD</a>-->
<!--                               <a href="https://en.wikipedia.org/wiki/Vyttila">VYTTILA</a>-->

<!--            </div>-->
<!--        </div>-->

<!--</div>-->
<!--</div>-->
<!--    </nav>-->
<!--&lt;!&ndash;&lt;!&ndash; Background image &ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;<div&ndash;&gt;-->
<!--&lt;!&ndash;  class="bg-image"&ndash;&gt;-->
<!--&lt;!&ndash;  style="&ndash;&gt;-->
<!--&lt;!&ndash;    background-image: url('https://mdbcdn.b-cdn.net/img/new/fluid/nature/012.webp');&ndash;&gt;-->
<!--&lt;!&ndash;    height: 100vh;&ndash;&gt;-->
<!--&lt;!&ndash;  "&ndash;&gt;-->
<!--&lt;!&ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;    <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->

<!--&lt;!&ndash;    <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->



<!--&lt;!&ndash;  <div class="mask" style="background-color:violet;">&ndash;&gt;-->
<!--&lt;!&ndash;    <div class="d-flex justify-content-center align-items-center h-100">&ndash;&gt;-->
<!--&lt;!&ndash;<br>&ndash;&gt;-->
<!--&lt;!&ndash;      <h2 class="text-black mb-0">Indian bank</h2>&ndash;&gt;-->

<!--&lt;!&ndash;         <a class="" href="{% url 'bankapp:link' %}"><h3>Click here...<br>&ndash;&gt;-->
<!--&lt;!&ndash;             <br><br>&ndash;&gt;-->
<!--&lt;!&ndash;             To accept the application&ndash;&gt;-->

<!--&lt;!&ndash;         </h3></a>&ndash;&gt;-->

<!--&lt;!&ndash;    </div>&ndash;&gt;-->
<!--&lt;!&ndash;  </div>&ndash;&gt;-->
<!--&lt;!&ndash;</div>&ndash;&gt;-->
<!--&lt;!&ndash; Background image &ndash;&gt;-->

<!--&lt;!&ndash; Background image &ndash;&gt;-->


<!-- <div class="bg-image d-flex justify-content-center align-items-center"-->
<!--style="-->
<!--    background-image: url('https://mdbcdn.b-cdn.net/img/new/fluid/nature/015.webp');-->
<!--   height: 100vh;-->
<!--">-->


<!--<br>-->
<!--        <br>-->
<!--         <br>-->

<!--   <h4 class="text-white">  Indian Bank&ndash;&gt;-->
<!--        <br>-->
<!--    </h4>-->
<!--         <a class="" href="{% url 'bankapp:link' %}"><h3>Click here...<br>-->
<!--             <br>-->
<!--             To accept the application&ndash;&gt;-->

<!--        </h3></a>-->


<!--&lt;!&ndash; - &ndash;&gt;-->
<!--&lt;!&ndash;    <br>&ndash;&gt;-->
<!--&lt;!&ndash;    <br>&ndash;&gt;-->
<!--&lt;!&ndash;</div>&ndash;&gt;-->

<!--&lt;!&ndash;      Indian Bank&ndash;&gt;-->
<!--&lt;!&ndash;        <br>&ndash;&gt;-->
<!--&lt;!&ndash;    </h4>&ndash;&gt;-->
<!--&lt;!&ndash;         <a class="" href="{% url 'bankapp:link' %}"><h3>Click here...<br>&ndash;&gt;-->
<!--&lt;!&ndash;             <br>&ndash;&gt;-->
<!--&lt;!&ndash;             To accept the application&ndash;&gt;-->

<!--&lt;!&ndash;         </h3></a>&ndash;&gt;-->



<!--&lt;!&ndash;    <br>&ndash;&gt;-->
<!--&lt;!&ndash;    <br>&ndash;&gt;-->
<!--</div>-->




<!--</div>-->
<!--</html>-->

bankproject/bankapp/templates/image.html
{% extends 'base.html' %}
{% load static %}
<div>
<img src="{% static 'img/ben.png' %}" >
</div>
<br>

bankproject/bankapp/templates/link.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<link href="{% static 'css/log.css' %}" rel="stylesheet">
<br>
<br>
<h2> Your Application is successfully accepted</h2>
<br>
<br>
<br>
<a href="{% url 'bankapp:home' %}"><h1>Home</h1> </a>
</body>
</html>

bankproject/bankapp/templates/login.html
{% load static %}


<div class="container" xmlns="http://www.w3.org/1999/html">
	<div class="screen">
		<div class="screen__content">
                <link href="{% static 'css/style.css' %}" rel="stylesheet">

<form action ="login" method="post">
    {% csrf_token %}
	<br>
	<br>
	<br>
	<br>
	<br>
    <input type="text" name="username" placeholder="Enter username">Username<br><br>
	<br>

    <input type="password" name="password"  placeholder="Enter password">Password<br><br>
	<br>
	<br>
    <input type="submit">
</form>
			<br>
			<br>
			<br>
			<br>

<!--			<form class="login">-->
<!--				<form action="login" method="post">-->
<!--                          {% csrf_token %}-->

<!--				<div class="login__field">-->
<!--					<i class="login__icon fas fa-user"></i>-->



<!--					<input type="text" class="login__input" placeholder="User name / Email">-->
<!--				</div>-->
<!--				<div class="login__field">-->
<!--					<i class="login__icon fas fa-lock"></i>-->
<!--					<input type="password" class="login__input" placeholder="Password">-->
<!--				</div>-->

<!--&lt;!&ndash;				<button class="button login__submit">&ndash;&gt;-->
<!--					<input type="submit">-->
<!--					<i class="button__icon fas fa-chevron-right"></i>-->
<!--				</button>-->
			</form></form></div><a class="btn btn-warning" href="{% url 'bankapp:register' %}"> Register </a><br>
			<br>
			<br>
			<br>
                   <a class="btn btn-danger" href="{% url 'bankapp:logout' %}">Logout       </a>
			<div class="social-login">

				<div class="social-icons">
					<a href="#" class="social-login__icon fab fa-instagram"></a>
					<a href="#" class="social-login__icon fab fa-facebook"></a>
					<a href="#" class="social-login__icon fab fa-twitter"></a>
				</div>
			</div>
		</div>

		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div></link>

bankproject/bankapp/templates/logout.html
{% load static %}


<link href="{% static 'css/log.css' %}" rel="stylesheet">
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1>You are successfully loggedout.</h1>
<br>
<br>
<h2>Thankyou..</h2><br>
<br>
<h3>Visit again . . .</h3>

bankproject/bankapp/templates/navbar.html
{% load static %}

<html>
 <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<!--    <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--<script src= "https://kit.fontawesome.com/cae219a7d3.js"> </script>-->

<br>INDIAN BANK

   <div>      <a class="btn btn-warning" href="{% url 'bankapp:login' %}">Login   </a></div>
<br>
        <div>  <a class="btn btn-warning" href="{% url 'bankapp:register' %}"> Register  </a></div><br>
{% if user.is_authenticated %}
									<li>Hello....
                                        {{user.username}}</li>
      <a href="logout">Logout</a>{% endif %}



<div class="dropdown">
<link rel="stylesheet" href="{% static 'css/d.css' %}">
      <button>Branches</button>

<div class="dropdown-content">





                           <a href="https://en.wikipedia.org/wiki/Kochi">KOCHI</a>
                            <a href="https://en.wikipedia.org/wiki/Aluva">ALUVA</a>
                             <a href="https://en.wikipedia.org/wiki/Angamaly"> ANGAMALY</a>
                              <a href="https://en.wikipedia.org/wiki/Kakkanad">KAKKANAD</a>
                               <a href="https://en.wikipedia.org/wiki/Vyttila">VYTTILA</a>

            </div>
        </div>

</div>
</div>
    </nav>
<!--&lt;!&ndash; Background image &ndash;&gt;-->
<!--<div-->
<!--  class="bg-image"-->
<!--  style="-->
<!--    background-image: url('https://mdbcdn.b-cdn.net/img/new/fluid/nature/012.webp');-->
<!--    height: 100vh;-->
<!--  "-->
<!--&gt;-->
<!--    <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->

<!--    <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->



<!--  <div class="mask" style="background-color:violet;">-->
<!--    <div class="d-flex justify-content-center align-items-center h-100">-->
<!--<br>-->
<!--      <h2 class="text-black mb-0">Indian bank</h2>-->

<!--         <a class="" href="{% url 'bankapp:link' %}"><h3>Click here...<br>-->
<!--             <br><br>-->
<!--             To accept the application-->

<!--         </h3></a>-->

<!--    </div>-->
<!--  </div>-->
<!--</div>-->
<!-- Background image -->

<!-- Background image -->


 <div class="bg-image d-flex justify-content-center align-items-center"
style="
    background-image: url('https://mdbcdn.b-cdn.net/img/new/fluid/nature/015.webp');
   height: 100vh;
">


<br>
        <br>
         <br>

   <h4 class="text-white">  Indian Bank-->
        <br>
    </h4>

         <a class="" href="{% url 'bankapp:link' %}"><h3>Click here...<br>
             <br>
             To accept the application-->
<a class="" href="{% url 'bankapp:form' %}">Submit Form</a>
        </h3></a>


<!-- - --><>
<!--    <br>-->
<!--</div>-->

<!--      Indian Bank-->
<!--        <br>-->
<!--    </h4>-->
<!--         <a class="" href="{% url 'bankapp:link' %}"><h3>Click here...<br>-->
<!--             <br>-->
<!--             To accept the application-->

<!--         </h3></a>-->



<!--    <br>-->
<!--    <br>-->
</div>




</div>
</html>

bankproject/bankapp/templates/register.html
{% load static %}

<div class="container" xmlns="http://www.w3.org/1999/html">
        <div class="row">
              <link href="{% static 'css/text.css' %}" rel="stylesheet">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    REGISTER
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">

                            <form action ="register" method="post">
                                {% csrf_token %}
<!--                            <div class="form-group">-->


<!--                                <label class="form-control-label">username</label>-->

<!--                                <input type="text"  name="username">-->



<!--                            </div>-->
<!--                            <div class="form-group">-->

<!--                                <label class="form-control-label">password</label>-->
<!--                                    <input type="password"  name="password">-->


<!--                            </div>-->
<!--                            <div class="form-group">-->

<!--                                <label class="form-control-label">confirmpassword</label>-->
<!--                                    <input type="password" name="password1">-->

                                <input  type="text" name="username" id="username" placeholder="enter your username"><br>
    <input  type="text" name="first_name" placeholder="enter your firstname"><br>
    <input  type="text" name="last_name" placeholder="enter your lastname"><br>
    <input  type="text" name="email" placeholder="enter your email address"><br>
    <input  type="password" name="password" placeholder="enter your password"><br>
    <input  type="password" name="password1" placeholder="confirm password"><br>
                            <div class="col-lg-12 loginbttm">

                                    <!-- Error Message -->

                                <div class="col-lg-6 login-btm login-button">
                                    <input type="submit">
                                    {% for  msg in messages %}<h2>{{msg}}</h2>
                               {% endfor %}
                                </div>
                            </div></form>


                                </div>
                            </div>


                                    <a class="btn btn-danger" href="{% url 'bankapp:form' %}"> Registration form </a>
                                </div>

                            </div>


                    </div>
                </div>
              <div class="col-lg-3 col-md-2"></div>
            </div>